hylook_main_homepage:
    path:     /{_locale}
    defaults: { _controller: hylookMainBundle:Default:index, _locale: es_ES }
    requirements:
        _locale: en_US|es_ES    
hylook_main_lector:
    pattern: /{_locale}/lector/
    defaults: { _controller: hylookMainBundle:Default:lector, _locale: es_ES  }
    requirements:
        _locale: en_US|es_ES
    
hylook_main_grupos:
    pattern: /{_locale}/grupos/
    defaults: { _controller: hylookMainBundle:Default:grupos, _locale: es_ES  }
    requirements:
        _locale: en_US|es_ES      

hylook_main_addOneEmisor:
    path: /{_locale}/emisor/addOne/{nombre}/{descripcion}
    defaults: {_controller: hylookMainBundle:Default:addOne, nombre:desconocido, descripcion:sin datos, _locale: es_ES  }
    requirements:
        _locale: en_US|es_ES
    
hylook_main_allEmisor:
    path: /{_locale}/emisor/all
    defaults: {_controller: hylookMainBundle:Default:getAll, _locale: es_ES  }
    requirements:
        _locale: en_US|es_ES    
   
hylook_main_oneEmisor:
    path: /{_locale}/emisor/ficha/{id}
    defaults: {_controller: hylookMainBundle:Default:getById, _locale: es_ES  }
    requirements:
        _locale: en_US|es_ES     

hylook_main_emisor:
    pattern: /{_locale}/emisor/
    defaults: { _controller: hylookMainBundle:Default:emisor, _locale: es_ES  }
    requirements:
        _locale: en_US|es_ES
  
usuario_registro:
    pattern: /{_locale}/registro
    defaults: { _controller: hylookMainBundle:Default:registro, _locale: es_ES  }
    requirements:
        _locale: en_US|es_ES

new_emisor:
    pattern: /{_locale}/emisor/new
    defaults: { _controller: hylookMainBundle:Default:newemisor, _locale: es_ES  }
    requirements:
        _locale: en_US|es_ES 
     
new_lector:
    pattern: /{_locale}/lector/new
    defaults: { _controller: hylookMainBundle:Default:newlector, _locale: es_ES  }
    requirements:
        _locale: en_US|es_ES    